#!/bin/bash

all:
	cd pflayer && make && cd ..;
	cd amlayer && make && cd ..;
	cd dblayer && make && cd ..;

clean:
	cd pflayer && make clean && cd ..;
	cd amlayer && make clean && cd ..;
	cd dblayer && make clean && cd ..;
